// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWpeQwOVQ_SCeWMv6DbkoCo7cjwgc1O4',
    appId: '1:426427613550:web:1795ced55471076ae5417f',
    messagingSenderId: '426427613550',
    projectId: 'bazaar-c824e',
    authDomain: 'bazaar-c824e.firebaseapp.com',
    storageBucket: 'bazaar-c824e.firebasestorage.app',
    measurementId: 'G-D7DT2MX4K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Gm87tSXNXPxwjMkcPzFfETA87uZSals',
    appId: '1:426427613550:android:888af6d9f9559403e5417f',
    messagingSenderId: '426427613550',
    projectId: 'bazaar-c824e',
    storageBucket: 'bazaar-c824e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBODx8WMFw2J6I7rJkVlgZCZBqDSzZPKEQ',
    appId: '1:426427613550:ios:3617de2dd2181459e5417f',
    messagingSenderId: '426427613550',
    projectId: 'bazaar-c824e',
    storageBucket: 'bazaar-c824e.firebasestorage.app',
    iosBundleId: 'com.example.getxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBODx8WMFw2J6I7rJkVlgZCZBqDSzZPKEQ',
    appId: '1:426427613550:ios:3617de2dd2181459e5417f',
    messagingSenderId: '426427613550',
    projectId: 'bazaar-c824e',
    storageBucket: 'bazaar-c824e.firebasestorage.app',
    iosBundleId: 'com.example.getxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWpeQwOVQ_SCeWMv6DbkoCo7cjwgc1O4',
    appId: '1:426427613550:web:8b12b56ee5bc49d2e5417f',
    messagingSenderId: '426427613550',
    projectId: 'bazaar-c824e',
    authDomain: 'bazaar-c824e.firebaseapp.com',
    storageBucket: 'bazaar-c824e.firebasestorage.app',
    measurementId: 'G-6LWYQPTNCE',
  );
}
